const translations = {
  ro: {
    // ---------------- CONT.HTML ----------------
    authTitle: "🔬 Autentificare BioBAC",
    loginBtn: "➡️ Log In",
    signupBtn: "✨ Creează cont",
    accountTitle: "👩‍🔬 Contul Meu",
    saveBtn: "💾 Salvează numele",
    saveEmailBtn: "📧 Salvează email",
    changePassBtn: "🔁 Schimbă parola",
    logoutBtn: "🚪 Deconectare",
    langBtn: "🌐 Schimbă limbă",
    darkModeBtn: "🌓 Dark Mode",
    deleteAccountBtn: "🗑️ Șterge contul",
    labelName: "Schimbă numele",
    labelEmail: "Schimbă email-ul",
    labelPassword: "Schimbă parola",
    placeholderRegisterName: "Nume complet",
    placeholderEmail: "Email",
    placeholderPassword: "Parolă",
    placeholderEditName: "Nume nou",
    placeholderEditEmail: "Email nou",
    placeholderNewPassword: "Parolă nouă",
    nameLabel: "👤 Nume:",
    emailLabel: "✉️ Email:",
    alerts: {
      fillAllFields: "⚠️ Completează toate câmpurile!",
      fillEmailPassword: "⚠️ Completează email și parola!",
      invalidName: "⚠️ Eroare: nume invalid.",
      invalidEmail: "⚠️ Eroare: email invalid.",
      invalidPassword: "⚠️ Parolă invalidă.",
      accountCreated: "✅ Cont creat cu succes!",
      loginSuccess: "✅ Autentificare reușită!",
      nameUpdated: "✅ Numele a fost actualizat!",
      emailUpdated: "✅ Email-ul a fost actualizat!",
      passwordChanged: "🔐 Parola a fost schimbată!",
      confirmDelete: "Ești sigur că vrei să-ți ștergi contul?",
      accountDeleted: "✅ Contul a fost șters."
    },

    // ---------------- INDEX.HTML ----------------
    menuTitle: "📘 BioBAC – Meniu principal",
    chooseLesson: "Alege o lecție pentru a începe învățarea:",
    section1: "🌿 Biologie vegetală și animală",
    section2: "🧠 Anatomie umană",
    section3: "🔬 Modele 3D AR interactive",
    section4: "📊 Teste recapitulative",
    despre: "Despre BioBAC",
    aflaMaiMulte: "→ Află mai multe",
    celula: "Celula vegetală și animală",
    tesuturi: "Țesuturi",
    fotosinteza: "Fotosinteza",
    organe: "Organe și funcții",
    reproducerea: "Reproducerea",
    organizare: "Organizarea corpului uman",
    nervos: "Sistemul nervos",
    locomotor: "Sistemul locomotor",
    digestiv: "Sistemul digestiv",
    respirator: "Sistemul respirator",
    circulator: "Sistemul circulator",
    excretor: "Sistemul excretor",
    reproducator: "Sistemul reproducător",
    endocrine: "Glandele endocrine",
    analizatori: "Analizatorii",
    inimaAR: "Inima în Realitate Augmentată",
    neuronaAR: "Celulă neuronală în AR",
    ochiAR: "Ochiul uman în AR",
    testBio: "Test recapitulativ – Biologie",
    testAnat: "Test recapitulativ – Anatomie",
    intraLectie: "→ Intră în lecție",
    vizAR: "→ Vizualizează în AR",
    incepeTest: "→ Începe testul",

    // ---------------- CELULA.HTML ----------------
    celula: {
      titlu_fereastra: "BioBAC – Lecția: Celula",
      titlu_pagina: "🔬 BioBAC – Lecția: Celula",
      teorie_titlu: "🧠 Teorie esențială",
      teorie_1: "Celula este unitatea structurală și funcțională a organismelor vii.",
      teorie_2: "Celulele pot fi vegetale sau animale, având componente comune și diferențe specifice.",
      teorie_3: "Organite comune: membrană, citoplasmă, nucleu, mitocondrii, ribozomi.",
      teorie_4: "Specifice celulei vegetale: perete celular, cloroplaste, vacuole mari.",
      teorie_5: "Specifice celulei animale: centriol, vacuole mici.",
      test_titlu: "📝 Test – 9 itemi",

      intrebare_1: "1. Ce organit produce energie în celulă?",
      intrebare_1_rasp_1: "Mitocondria",
      intrebare_1_rasp_2: "Ribozomul",
      intrebare_1_rasp_3: "Lizozomul",
      intrebare_1_rasp_4: "Nucleul",

      intrebare_2: "2. Ce structură lipsește din celula animală?",
      intrebare_2_rasp_1: "Peretele celular",
      intrebare_2_rasp_2: "Citoplasma",
      intrebare_2_rasp_3: "Ribozomii",
      intrebare_2_rasp_4: "Mitocondriile",

      intrebare_3: "3. Completează: Informația genetică se află în __________.",
      verifica_buton: "Verifică",

      intrebare_4: "4. Alege toate structurile celulei vegetale:",
      intrebare_4_optiune_1: "Perete celular",
      intrebare_4_optiune_2: "Cloroplaste",
      intrebare_4_optiune_3: "Centriol",
      intrebare_4_optiune_4: "Vacuole mari",

      intrebare_5: "5. Completează: Ribozomii sunt implicați în __________ proteinelor.",

      intrebare_6: "6. Ce este celula?",

      intrebare_7: "7. Care dintre următoarele se găsesc în ambele tipuri de celule?",
      intrebare_7_optiune_1: "Membrană plasmatică",
      intrebare_7_optiune_2: "Cloroplaste",
      intrebare_7_optiune_3: "Mitocondrii",
      intrebare_7_optiune_4: "Perete celular",

      intrebare_8: "8. Asociază fiecare structură cu rolul său:",
      intrebare_8_label_1: "Mitocondrie →",
      intrebare_8_label_2: "Nucleu →",
      selectaaza: "Selectează",
      intrebare_8_rasp_energie: "Producerea energiei",
      intrebare_8_rasp_informatie: "Păstrarea informației",

      intrebare_9: "9. Ce tip de celule conțin centrioli?",
      intrebare_9_rasp_1: "Celulele animale",
      intrebare_9_rasp_2: "Celulele vegetale",
      intrebare_9_rasp_3: "Ambele",
      intrebare_9_rasp_4: "Niciuna"
    },

    general: {
      inapoi: "← Înapoi la meniu"
    }
  },

  en: {
    // ---------------- CONT.HTML ----------------
    authTitle: "🔬 BioBAC Login",
    loginBtn: "➡️ Log In",
    signupBtn: "✨ Sign Up",
    accountTitle: "👩‍🔬 My Account",
    saveBtn: "💾 Save Name",
    saveEmailBtn: "📧 Save Email",
    changePassBtn: "🔁 Change Password",
    logoutBtn: "🚪 Log Out",
    langBtn: "🌐 Change Language",
    darkModeBtn: "🌓 Dark Mode",
    deleteAccountBtn: "🗑️ Delete Account",
    labelName: "Change Name",
    labelEmail: "Change Email",
    labelPassword: "Change Password",
    placeholderRegisterName: "Full Name",
    placeholderEmail: "Email",
    placeholderPassword: "Password",
    placeholderEditName: "New Name",
    placeholderEditEmail: "New Email",
    placeholderNewPassword: "New Password",
    nameLabel: "👤 Name:",
    emailLabel: "✉️ Email:",
    alerts: {
      fillAllFields: "⚠️ Please fill in all fields!",
      fillEmailPassword: "⚠️ Please fill in email and password!",
      invalidName: "⚠️ Error: invalid name.",
      invalidEmail: "⚠️ Error: invalid email.",
      invalidPassword: "⚠️ Invalid password.",
      accountCreated: "✅ Account created successfully!",
      loginSuccess: "✅ Login successful!",
      nameUpdated: "✅ Name has been updated!",
      emailUpdated: "✅ Email has been updated!",
      passwordChanged: "🔐 Password has been changed!",
      confirmDelete: "Are you sure you want to delete your account?",
      accountDeleted: "✅ Account has been deleted."
    },

    // ---------------- INDEX.HTML ----------------
    menuTitle: "📘 BioBAC – Main Menu",
    chooseLesson: "Choose a lesson to start learning:",
    section1: "🌿 Plant and Animal Biology",
    section2: "🧠 Human Anatomy",
    section3: "🔬 3D AR Interactive Models",
    section4: "📊 Review Tests",
    despre: "About BioBAC",
    aflaMaiMulte: "→ Learn more",
    celula: "Plant and Animal Cell",
    tesuturi: "Tissues",
    fotosinteza: "Photosynthesis",
    organe: "Organs and Functions",
    reproducerea: "Reproduction",
    organizare: "Human Body Organization",
    nervos: "Nervous System",
    locomotor: "Locomotor System",
    digestiv: "Digestive System",
    respirator: "Respiratory System",
    circulator: "Circulatory System",
    excretor: "Excretory System",
    reproducator: "Reproductive System",
    endocrine: "Endocrine Glands",
    analizatori: "Analyzers",
    inimaAR: "Heart in Augmented Reality",
    neuronaAR: "Neuron Cell in AR",
    ochiAR: "Human Eye in AR",
    testBio: "Review Test – Biology",
    testAnat: "Review Test – Anatomy",
    intraLectie: "→ Enter Lesson",
    vizAR: "→ View in AR",
    incepeTest: "→ Start Test",

    // ---------------- CELULA.HTML ----------------
    celula: {
      titlu_fereastra: "BioBAC – Lesson: Cell",
      titlu_pagina: "🔬 BioBAC – Lesson: Cell",
      teorie_titlu: "🧠 Essential Theory",
      teorie_1: "The cell is the structural and functional unit of living organisms.",
      teorie_2: "Cells can be plant or animal, having common components and specific differences.",
      teorie_3: "Common organelles: membrane, cytoplasm, nucleus, mitochondria, ribosomes.",
      teorie_4: "Specific to plant cells: cell wall, chloroplasts, large vacuoles.",
      teorie_5: "Specific to animal cells: centriole, small vacuoles.",
      test_titlu: "📝 Test – 9 items",

      intrebare_1: "1. Which organelle produces energy in the cell?",
      intrebare_1_rasp_1: "Mitochondria",
      intrebare_1_rasp_2: "Ribosome",
      intrebare_1_rasp_3: "Lysosome",
      intrebare_1_rasp_4: "Nucleus",

      intrebare_2: "2. Which structure is missing from the animal cell?",
      intrebare_2_rasp_1: "Cell wall",
      intrebare_2_rasp_2: "Cytoplasm",
      intrebare_2_rasp_3: "Ribosomes",
      intrebare_2_rasp_4: "Mitochondria",

      intrebare_3: "3. Complete: Genetic information is located in the __________.",
      verifica_buton: "Check",

      intrebare_4: "4. Choose all plant cell structures:",
      intrebare_4_optiune_1: "Cell wall",
      intrebare_4_optiune_2: "Chloroplasts",
      intrebare_4_optiune_3: "Centriole",
      intrebare_4_optiune_4: "Large vacuoles",

      intrebare_5: "5. Complete: Ribosomes are involved in __________ protein synthesis.",

      intrebare_6: "6. What is a cell?",

      intrebare_7: "7. Which of the following are found in both cell types?",
      intrebare_7_optiune_1: "Plasma membrane",
      intrebare_7_optiune_2: "Chloroplasts",
      intrebare_7_optiune_3: "Mitochondria",
      intrebare_7_optiune_4: "Cell wall",

      intrebare_8: "8. Match each structure with its role:",
      intrebare_8_label_1: "Mitochondria →",
      intrebare_8_label_2: "Nucleus →",
      selectaaza: "Select",
      intrebare_8_rasp_energie: "Energy production",
      intrebare_8_rasp_informatie: "Information storage",

      intrebare_9: "9. Which cell types contain centrioles?",
      intrebare_9_rasp_1: "Animal cells",
      intrebare_9_rasp_2: "Plant cells",
      intrebare_9_rasp_3: "Both",
      intrebare_9_rasp_4: "None"
    },

    general: {
      inapoi: "← Back to menu"
    }
  }
};

